name: Deliver APK

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build APK]
    types:
      - completed  

jobs:
  build:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2.1.1
        with:
          dotnet-version: '8.0.x'

      - name: Download latest artifact
        run: gh run download ${{ github.event.workflow_run.id }} -R dotnet-websharper/capacitor -p "app-debug*" -D artifacts
        env:
          GH_TOKEN: ${{ github.token }}

      - name: List artifacts
        run: ls artifacts

      - name: Send notification
        run: dotnet fsi ./notification-helper.fsx
        env:
          DISCORD_PACKAGE_FEED: ${{ secrets.DISCORD_PACKAGE_FEED }}
          DISCORD_THREAD: ${{ secrets.DISCORD_THREAD }}
        shell: bash